# Fuente de datos Prometheus autoprovisionada en Grafana
# Issue #62 - Parte D
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
